# Generated by Django 4.1.1 on 2022-11-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "Can View History")],
            },
        ),
    ]
